preset: PSR2
risky: true
enabled:
  - whitespace_after_comma_in_array
  - unary_operator_spaces
  - trim_array_spaces
  - trailing_comma_in_multiline_array
  - ternary_operator_spaces
  - standardize_not_equals
  - space_after_semicolon
  - single_blank_line_before_namespace
  - simplified_null_return
  - short_scalar_cast
  - short_array_syntax
  - self_accessor
  - post_increment
  - print_to_echo
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_useless_inheritdoc
  - phpdoc_scalar
  - phpdoc_single_line_var_spacing
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - no_unneeded_control_parentheses
  - no_unused_imports
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - normalize_index_brace
  - object_operator_without_whitespace
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_spaces_inside_offset
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - native_function_casing
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - method_separation
  - magic_constant_casing
  - alpha_ordered_imports
  - lowercase_cast
  - function_typehint_space
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
  - declare_equal_normalize
  - cast_spaces
  - blank_line_after_opening_tag
  - blank_line_before_return
  - binary_operator_spaces
finder:
  exclude:
    - node_modules
    - runtime
    - vendor
  name: "*.php"
  not-name:
    - "*.blade.php"