name: buildcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.2
          - 7.3
          - 7.4
        prefer-lowest: [false]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extension-csv: mbstring, fileinfo #optional, setup extensions
          coverage: none #optional, setup coverage driver
          pecl: false #optional, setup PECL

      - name: Check Version
        run: php -v && php -m && composer -V

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies (composer.lock)
        if: false == matrix.prefer-lowest
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install dependencies (prefer-lowest)
        if: true == matrix.prefer-lowest
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-lowest

      - name: Run test suite
        run: composer exec -- phpunit -v
