name: phpcs

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, fileinfo
          coverage: none
          tools: cs2pr

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ env.php-versions }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ env.php-versions }}-
            ${{ runner.os }}-composer-

      - name: Check Version
        run: php -v && php -m && composer -V

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies (composer.lock)
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run phpcs fix
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr